const express = require('express');
const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const { Server } = require('socket.io');
const cors = require('cors');
const mediasoup = require('mediasoup');

const app = express();
app.use(cors());

// Automatically detect SSL certificates generated by the Next.js client
let server;
const certPath = path.join(__dirname, '../client/certificates/localhost.pem');
const keyPath = path.join(__dirname, '../client/certificates/localhost-key.pem');

if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
  try {
    const options = {
      key: fs.readFileSync(keyPath),
      cert: fs.readFileSync(certPath)
    };
    server = https.createServer(options, app);
    console.log('🔑 SSL Certificates found in client directory. Starting server in HTTPS mode...');
  } catch (err) {
    console.error('⚠️ Failed to load SSL certificates, falling back to HTTP:', err.message);
    server = http.createServer(app);
  }
} else {
  server = http.createServer(app);
  console.log('🔓 Starting server in HTTP mode (no SSL certificates found)...');
}

// Dynamic allowed origins for development and local network testing
const allowedOrigins = [
  'http://localhost:3000',
  'https://localhost:3000',
  'http://127.0.0.1:3000',
  'https://127.0.0.1:3000',
];

if (process.env.FRONTEND_URL) {
  allowedOrigins.push(process.env.FRONTEND_URL);
  if (process.env.FRONTEND_URL.startsWith('https://')) {
    allowedOrigins.push(process.env.FRONTEND_URL.replace('https://', 'http://'));
  } else if (process.env.FRONTEND_URL.startsWith('http://')) {
    allowedOrigins.push(process.env.FRONTEND_URL.replace('http://', 'https://'));
  }
}

const io = new Server(server, {
  cors: {
    origin: (origin, callback) => {
      if (!origin || allowedOrigins.indexOf(origin) !== -1 || 
          origin.startsWith('http://localhost') || 
          origin.startsWith('https://localhost') || 
          origin.startsWith('http://192.168.') || 
          origin.startsWith('https://192.168.')) {
        callback(null, true);
      } else {
        callback(new Error('Not allowed by CORS'));
      }
    },
    methods: ['GET', 'POST'],
    credentials: true
  }
});


let worker;
let rooms = {}; // roomId -> { router, peers: { peerId: { transports, producers, consumers } } }

// Media codecs required for WebRTC audio/video
const mediaCodecs = [
  {
    kind: 'audio',
    mimeType: 'audio/opus',
    clockRate: 48000,
    channels: 2
  },
  {
    kind: 'video',
    mimeType: 'video/VP8',
    clockRate: 90000,
    parameters: {
      'x-google-start-bitrate': 1000
    }
  }
];

async function createWorker() {
  worker = await mediasoup.createWorker({
    logLevel: 'warn',
    rtcMinPort: 2000,
    rtcMaxPort: 10000,
  });

  worker.on('died', () => {
    console.error('Mediasoup worker died');
    process.exit(1);
  });
}

app.get('/', (req, res) => {
  res.send('RTC Server Running');
});

app.get('/rooms/:roomId/participants', (req, res) => {
  const { roomId } = req.params;
  const room = rooms[roomId];
  if (!room || !room.peers) {
    return res.json({ participants: [] });
  }
  const participants = Object.keys(room.peers).map(socketId => {
    const peer = room.peers[socketId];
    return {
      socketId,
      userId: peer.userId,
      role: peer.role
    };
  });
  res.json({ participants });
});

io.on('connection', (socket) => {
  console.log('User connected:', socket.id);

  socket.on('subscribeRoomPreview', ({ roomId }, callback) => {
    socket.roomId = roomId;
    socket.join(roomId);
    
    const room = rooms[roomId];
    if (!room || !room.peers) {
      return callback({ participants: [] });
    }
    const participantsList = Object.keys(room.peers).map(socketId => {
      const peer = room.peers[socketId];
      return {
        socketId,
        userId: peer.userId,
        role: peer.role
      };
    });
    callback({ participants: participantsList });
  });

  // 1. Join Room & Return Router RTP Capabilities
  socket.on('joinRoom', async ({ roomId, mediaState, role, userId }, callback) => {
    try {
      if (!worker) {
        console.error('Mediasoup worker is not initialized yet');
        return callback({ error: 'Worker not ready' });
      }

      socket.roomId = roomId;
      await socket.join(roomId);

      if (!rooms[roomId]) {
        const router = await worker.createRouter({ mediaCodecs });
        rooms[roomId] = { router, peers: {} };
      }

      // Check if this userId already has an active peer connection in this room
      const room = rooms[roomId];
      if (room && userId) {
        for (const existingSocketId in room.peers) {
          const peer = room.peers[existingSocketId];
          if (peer.userId === userId && existingSocketId !== socket.id) {
            console.log(`Clearing stale session for userId: ${userId} (old socket: ${existingSocketId})`);
            
            // Notify the old socket that they are being disconnected due to duplicate login
            io.to(existingSocketId).emit('duplicate-session');
            const oldSocket = io.sockets.sockets.get(existingSocketId);
            if (oldSocket) {
              oldSocket.disconnect(true);
            }

            // Clean up all transports of the old stale session
            for (const transportId in peer.transports) {
              try {
                peer.transports[transportId].close();
              } catch (e) {
                console.warn(`Error closing stale transport:`, e);
              }
            }
            
            // Delete the stale peer
            delete room.peers[existingSocketId];
            
            // Notify others to clean up the stale peer immediately
            socket.to(roomId).emit('user-disconnected', existingSocketId);
          }
        }
      }

      rooms[roomId].peers[socket.id] = {
        transports: {},
        producers: {},
        consumers: {},
        mediaState: mediaState || { video: true, audio: true },
        role: role || 'student',
        userId: userId || socket.id
      };

      socket.to(roomId).emit('user-joined', {
        userId: socket.id,
        mediaState: mediaState || { video: true, audio: true },
        role: role || 'student'
      });

      const router = rooms[roomId].router;
      const participants = Object.keys(rooms[roomId].peers);

      const peerMediaStates = {};
      const peerRoles = {};
      for (const peerId in rooms[roomId].peers) {
        peerMediaStates[peerId] = rooms[roomId].peers[peerId].mediaState || { video: true, audio: true };
        peerRoles[peerId] = rooms[roomId].peers[peerId].role || 'student';
      }

      callback({ rtpCapabilities: router.rtpCapabilities, participants, peerMediaStates, peerRoles });
    } catch (err) {
      console.error('[joinRoom] Error:', err);
      callback({ error: err.message });
    }
  });

  // 2. Create WebRTC Transport (For Sending or Receiving)
  socket.on('createWebRtcTransport', async ({ sender, hostname }, callback) => {
    try {
      if (!socket.roomId || !rooms[socket.roomId]) {
        console.warn(`[createWebRtcTransport] Room not found for socket ${socket.id}`);
        return callback({ error: 'Room not found' });
      }
      const room = rooms[socket.roomId];
      const peer = room.peers[socket.id];
      if (!peer) {
        console.warn(`[createWebRtcTransport] Peer not found for socket ${socket.id} in room ${socket.roomId}`);
        return callback({ error: 'Peer not registered' });
      }

      const router = room.router;

      // Dynamically bind to the exact interface IP/hostname the client is using to connect
      let localIp = '127.0.0.1';

      if (hostname && hostname !== 'localhost' && hostname !== '127.0.0.1') {
        localIp = hostname;
      } else if (process.env.ANNOUNCED_IP) {
        localIp = process.env.ANNOUNCED_IP;
      }

      const transport = await router.createWebRtcTransport({
        listenIps: [
          {
            ip: '0.0.0.0',
            announcedIp: localIp
          }
        ],
        enableUdp: true,
        enableTcp: true,
        preferUdp: true,
      });

      transport.on('dtlsstatechange', dtlsState => {
        if (dtlsState === 'closed') transport.close();
      });

      transport.on('close', () => {
        console.log('transport closed');
      });

      // Store the transport safely
      peer.transports[transport.id] = transport;

      callback({
        id: transport.id,
        iceParameters: transport.iceParameters,
        iceCandidates: transport.iceCandidates,
        dtlsParameters: transport.dtlsParameters,
      });
    } catch (err) {
      console.error('[createWebRtcTransport] Error:', err);
      callback({ error: err.message });
    }
  });

  // 3. Connect Transport
  socket.on('transport-connect', async ({ transportId, dtlsParameters }, callback) => {
    try {
      if (!socket.roomId || !rooms[socket.roomId] || !rooms[socket.roomId].peers[socket.id]) {
        return callback({ error: 'Session not active' });
      }
      const transport = rooms[socket.roomId].peers[socket.id].transports[transportId];
      if (!transport) {
        return callback({ error: 'Transport not found' });
      }
      await transport.connect({ dtlsParameters });
      callback();
    } catch (err) {
      console.error('[transport-connect] Error:', err);
      callback({ error: err.message });
    }
  });

  // 4. Produce Media (Sender)
  socket.on('transport-produce', async ({ transportId, kind, rtpParameters, appData }, callback) => {
    try {
      if (!socket.roomId || !rooms[socket.roomId] || !rooms[socket.roomId].peers[socket.id]) {
        return callback({ error: 'Session not active' });
      }
      const room = rooms[socket.roomId];
      const peer = room.peers[socket.id];
      const transport = peer.transports[transportId];
      if (!transport) {
        return callback({ error: 'Transport not found' });
      }

      // Enforce single screen share per room
      if (appData && appData.mediaType === 'screen') {
        if (room.screenPresenter) {
          console.log(`[Screen Share] Rejecting screen share from socket ${socket.id} (already shared by ${room.screenPresenter.socketId})`);
          return callback({ error: 'Another user is already sharing their screen.' });
        }
      }

      const producer = await transport.produce({ kind, rtpParameters, appData });

      peer.producers[producer.id] = producer;

      // Track active screen share presenter
      if (appData && appData.mediaType === 'screen') {
        room.screenPresenter = {
          socketId: socket.id,
          producerId: producer.id
        };
        console.log(`[Screen Share] Socket ${socket.id} started screen sharing (producer: ${producer.id})`);
      }

      producer.on('transportclose', () => {
        producer.close();
      });

      // Broadcast to others in the room that a new producer is available
      socket.to(socket.roomId).emit('new-producer', {
        producerId: producer.id,
        peerId: socket.id,
        kind: producer.kind,
        appData: producer.appData
      });

      callback({ id: producer.id });
    } catch (err) {
      console.error('[transport-produce] Error:', err);
      callback({ error: err.message });
    }
  });

  // 5. Consume Media (Receiver)
  socket.on('consume', async ({ rtpCapabilities, transportId, producerId }, callback) => {
    try {
      if (!socket.roomId || !rooms[socket.roomId]) {
        return callback({ error: 'Room not found' });
      }
      const room = rooms[socket.roomId];
      const peer = room.peers[socket.id];
      if (!peer) {
        return callback({ error: 'Peer not found' });
      }
      const router = room.router;
      const transport = peer.transports[transportId];
      if (!transport) {
        return callback({ error: 'Transport not found' });
      }

      if (!router.canConsume({ producerId, rtpCapabilities })) {
        console.error('Cannot consume');
        return callback({ error: 'cannot consume' });
      }

      const consumer = await transport.consume({
        producerId,
        rtpCapabilities,
        paused: true // Must be paused initially until frontend resumes
      });

      peer.consumers[consumer.id] = consumer;

      consumer.on('transportclose', () => {
        consumer.close();
      });

      consumer.on('producerclose', () => {
        socket.emit('producer-closed', { producerId });
        consumer.close();
      });

      callback({
        id: consumer.id,
        producerId,
        kind: consumer.kind,
        rtpParameters: consumer.rtpParameters,
      });
    } catch (err) {
      console.error('[consume] Error:', err);
      callback({ error: err.message });
    }
  });

  socket.on('resume-consumer', async ({ consumerId }, callback) => {
    try {
      if (socket.roomId && rooms[socket.roomId] && rooms[socket.roomId].peers[socket.id]) {
        const consumer = rooms[socket.roomId].peers[socket.id].consumers[consumerId];
        if (consumer) {
          await consumer.resume();
        }
      }
      if (callback) callback();
    } catch (err) {
      console.error('[resume-consumer] Error:', err);
      if (callback) callback({ error: err.message });
    }
  });

  socket.on('pause-consumer', async ({ consumerId }, callback) => {
    try {
      if (socket.roomId && rooms[socket.roomId] && rooms[socket.roomId].peers[socket.id]) {
        const consumer = rooms[socket.roomId].peers[socket.id].consumers[consumerId];
        if (consumer) {
          await consumer.pause();
        }
      }
      if (callback) callback();
    } catch (err) {
      console.error('[pause-consumer] Error:', err);
      if (callback) callback({ error: err.message });
    }
  });

  // 6. Get Existing Producers
  socket.on('getProducers', (data, callback) => {
    try {
      const producersList = [];
      if (socket.roomId && rooms[socket.roomId]) {
        const room = rooms[socket.roomId];

        for (const peerId in room.peers) {
          if (peerId !== socket.id) {
            const peerProducers = room.peers[peerId].producers;
            for (const producerId in peerProducers) {
              producersList.push({
                producerId: producerId,
                peerId: peerId,
                kind: peerProducers[producerId].kind,
                appData: peerProducers[producerId].appData
              });
            }
          }
        }
      }
      callback(producersList);
    } catch (err) {
      console.error('[getProducers] Error:', err);
      callback([]);
    }
  });

  // 7. Close Specific Producer (e.g. stop screen sharing)
  socket.on('closeProducer', ({ producerId }, callback) => {
    try {
      if (socket.roomId && rooms[socket.roomId] && rooms[socket.roomId].peers[socket.id]) {
        const room = rooms[socket.roomId];
        const peer = room.peers[socket.id];
        const producer = peer.producers[producerId];
        if (producer) {
          producer.close();
          delete peer.producers[producerId];

          if (room.screenPresenter && room.screenPresenter.producerId === producerId) {
            room.screenPresenter = null;
            console.log(`[Screen Share] Cleared screen presenter for room ${socket.roomId} (presenter stopped manually)`);
          }
        }
      }
      if (callback) callback();
    } catch (err) {
      console.error('[closeProducer] Error:', err);
      if (callback) callback({ error: err.message });
    }
  });

  // Relay media states (camera off/mic off) since SFU doesn't do UI state
  socket.on('toggle-media', (payload) => {
    if (socket.roomId && rooms[socket.roomId]) {
      const peer = rooms[socket.roomId].peers[socket.id];
      if (peer) {
        peer.mediaState = {
          ...(peer.mediaState || { video: true, audio: true }),
          [payload.type]: !payload.isOff
        };
      }
      socket.to(socket.roomId).emit('toggle-media', payload);
    }
  });

  socket.on('disconnect', () => {
    console.log('User disconnected:', socket.id);
    if (socket.roomId && rooms[socket.roomId]) {
      const room = rooms[socket.roomId];
      const peer = room.peers[socket.id];
      if (peer) {
        // Cleanup all transports (this cleans up producers and consumers too)
        for (const transportId in peer.transports) {
          peer.transports[transportId].close();
        }
        delete room.peers[socket.id];
      }

      // Clear screen presenter if they disconnected
      if (room.screenPresenter && room.screenPresenter.socketId === socket.id) {
        room.screenPresenter = null;
        console.log(`[Screen Share] Cleared screen presenter for room ${socket.roomId} (presenter disconnected)`);
      }

      socket.to(socket.roomId).emit('user-disconnected', socket.id);
    }
  });
});

(async () => {
  try {
    await createWorker();
    const PORT = process.env.PORT || 3001;
    server.listen(PORT, () => {
      console.log(`SFU Signalling server is running on port ${PORT}`);
    });
  } catch (err) {
    console.error('Failed to start SFU Signalling server:', err);
    process.exit(1);
  }
})();

// Graceful shutdown handling to free up port 3001 and close mediasoup workers
const gracefulShutdown = (signal) => {
  console.log(`\nReceived ${signal}. Shutting down gracefully...`);

  // Close the HTTP/Socket.io server
  server.close(() => {
    console.log('HTTP server closed.');
    if (worker) {
      worker.close();
      console.log('Mediasoup worker closed.');
    }
    process.exit(0);
  });

  // Force exit if graceful shutdown takes too long
  setTimeout(() => {
    console.error('Graceful shutdown timed out, forcing exit...');
    process.exit(1);
  }, 2000);
};

process.on('SIGINT', () => gracefulShutdown('SIGINT'));
process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
